In [1]:
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf

In [3]:
tf.constant([[1.,2.,3.], [4.,5.,6.]])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [4]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [5]:
tf.constant([[1.,2.,3.], [4.,5.,6.]])[:,]

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [6]:
t = tf.constant([[1.,2.,3.], [4.,5.,6.]])

In [7]:
t+10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [8]:
tf.transpose(t)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 4.],
       [2., 5.],
       [3., 6.]], dtype=float32)>

In [9]:
np_ar = np.array([2.,3.,4.])

In [10]:
tf.constant(np_ar)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 3., 4.])>

In [11]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [12]:
tf.constant(2.) + tf.constant(40)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2] name: 

In [13]:
tf.constant(2) + tf.constant(40, dtype=tf.float64)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a double tensor [Op:AddV2] name: 

In [14]:
t_var = tf.Variable([[1.,2.,3.],[2.,3.,4.]])

In [15]:
t_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [2., 3., 4.]], dtype=float32)>

In [16]:
t_var[0,1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 1., 42.,  3.],
       [ 2.,  3.,  4.]], dtype=float32)>

In [17]:
def huber_fn(y_true,y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error) < 1
    squared_loss = tf.square(error) / 2 
    linear_loss = tf.abs(error) - 0.5
    return tf.where(is_small_error, squared_loss, linear_loss)

In [18]:
model.compile(loss=huber_fn,optimizer="nadam")
model.fit(X_train,y_train)

NameError: name 'model' is not defined

In [19]:
def create_huber(delta=1.0):
    def huber_fn(y_true,y_pred):
        error = y_true - y_pred
        is_small_error = tf.abs(error) < delta
        squared_loss = tf.square(error) / 2
        linear_loss = delta * tf.abs(error) - delta**2/2
        return tf.where(is_small_error,squared_loss,linear_loss)
    return huber_fn

In [20]:
model.compile(loss=create_huber(delta=2.0), optimizer="nadam")

NameError: name 'model' is not defined

In [ ]:
def my_softplus(z): ## return value is just tf.nn.softplus(z)
    return tf.math.log(tf.exp(z) + 1.0)

def my_glorot_initializer(shape, dtype=tf.float32): 
    stddev = tf.sqrt(2. / (shape[0] + shape[1]))
    return tf.random.normal(shape, stddev=stddev, dtype=dtype)

def my_li_regularizer(weights):
    return tf.reduce_sum(tf.abs(0.01 * weights))

def positive_weights(weights):
    return tf.where(weights < 0, tf.zeros_like(weights), weights)

In [21]:
layer = keras.layers.Dense(100, activation = my_softplus, 
                           kernel_initializer = my_glorot_initializer,
                           kernel_regularizer = my_li_regularizer,
                           kernel_constraint = my_positive_weights)

NameError: name 'keras' is not defined