In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd

In [2]:
def generate_time_series(batch_size, n_steps):
    freq1, freq2, offsets1, offsets2 = np.random.rand(4, batch_size, 1)
    time = np.linspace(0,1,n_steps)

    series = 0.5 * np.sin(( time - offsets1) * (freq1 * 10 + 10)) #wave 1
    series += 0.5 * np.sin(( time - offsets2) * (freq2 * 20 + 20)) #2
    series += 0.1 * (np.random.rand(batch_size, n_steps) - 0.5) #noise
    return series[..., np.newaxis].astype(np.float32)

In [3]:
n_steps = 50
series = generate_time_series(10000,n_steps+1)

In [4]:
new_n_steps = 1
new_series = generate_time_series(10,new_n_steps+1)

In [5]:
new_series

array([[[ 0.35974616],
        [-0.54191613]],

       [[-0.08133569],
        [-0.12376945]],

       [[ 0.62980056],
        [-0.1490191 ]],

       [[-0.01977597],
        [-0.00918195]],

       [[ 0.5158635 ],
        [ 0.42392033]],

       [[ 0.2341435 ],
        [-0.7478467 ]],

       [[-0.295979  ],
        [ 0.8069518 ]],

       [[-0.5388288 ],
        [-0.18826964]],

       [[ 0.66146916],
        [-0.09796509]],

       [[-0.05722408],
        [ 0.2610839 ]]], dtype=float32)

In [6]:
X_train, y_train = series[:7000, :n_steps], series[:7000, -1]
X_valid, y_valid = series[7000:9000, :n_steps], series[7000:9000, -1]
X_valid, y_valid = series[7000:9000, :n_steps], series[7000:9000, -1]
X_valid, y_valid = series[9000:, :n_steps], series[9000:, -1]

In [7]:
y_pred = X_valid[:, -1]
np.mean(keras.losses.MeanSquaredError()(y_valid, y_pred))

np.float32(0.05942023)

In [8]:
model = keras.models.Sequential([
    keras.layers.Flatten(input_shape=[50,1]),
    keras.layers.Dense(1)])
model.compile(loss="mse",optimizer="sgd",metrics=["mae"])

C:\Users\Berkay\Desktop\ML_projects\LSTM_sentiment\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [9]:
history = model.fit(X_train,y_train,epochs=30,validation_data=(X_valid,y_valid))

Epoch 1/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 0.1277 - mae: 0.2682 - val_loss: 0.0400 - val_mae: 0.1598
Epoch 2/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0298 - mae: 0.1404 - val_loss: 0.0239 - val_mae: 0.1240
Epoch 3/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0207 - mae: 0.1171 - val_loss: 0.0193 - val_mae: 0.1114
Epoch 4/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0172 - mae: 0.1059 - val_loss: 0.0167 - val_mae: 0.1042
Epoch 5/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0149 - mae: 0.0984 - val_loss: 0.0145 - val_mae: 0.0974
Epoch 6/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0131 - mae: 0.0923 - val_loss: 0.0130 - val_mae: 0.0923
Epoch 7/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0118 - mae: 0.0876 - val_loss: 0.0117 - val_mae: 0.0877
Epoch 8/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0108 - mae: 0.0837 - val_loss: 0.0108 - val_mae: 0.0844
Epoch 9/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - lo

In [10]:
rnnmodel = keras.models.Sequential([
    keras.layers.SimpleRNN(1, input_shape=[None,1])
])

C:\Users\Berkay\Desktop\ML_projects\LSTM_sentiment\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [11]:
rnnmodel.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)               │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3 (12.00 B)

 Trainable params: 3 (12.00 B)

 Non-trainable params: 0 (0.00 B)

In [12]:
rnnmodel.compile(loss="mse",optimizer="sgd",metrics=["mae"])

In [13]:
history = rnnmodel.fit(X_train,y_train,epochs=30, validation_data=[X_valid,y_valid])

Epoch 1/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.1938 - mae: 0.3560 - val_loss: 0.0933 - val_mae: 0.2545
Epoch 2/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0684 - mae: 0.2185 - val_loss: 0.0558 - val_mae: 0.2001
Epoch 3/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0513 - mae: 0.1911 - val_loss: 0.0483 - val_mae: 0.1860
Epoch 4/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0462 - mae: 0.1812 - val_loss: 0.0446 - val_mae: 0.1784
Epoch 5/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0432 - mae: 0.1750 - val_loss: 0.0419 - val_mae: 0.1728
Epoch 6/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0408 - mae: 0.1700 - val_loss: 0.0398 - val_mae: 0.1682
Epoch 7/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0388 - mae: 0.1659 - val_loss: 0.0379 - val_mae: 0.1644
Epoch 8/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 0.0372 - mae: 0.1623 - val_loss: 0.0364 - val_mae: 0.1610
Epoch 9/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - lo

In [14]:
rnn_fully_model = keras.models.Sequential([
        keras.layers.SimpleRNN(20, return_sequences=True, input_shape=[None,1]),
        keras.layers.SimpleRNN(20, return_sequences=True),
        keras.layers.SimpleRNN(1)
])

In [15]:
rnn_fully_model.compile(loss="mse",optimizer="sgd",metrics=["mae"])

In [16]:
history = rnn_fully_model.fit(X_train,y_train, epochs=30, validation_data=[X_valid,y_valid])

Epoch 1/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 4s 10ms/step - loss: 0.1067 - mae: 0.2278 - val_loss: 0.0259 - val_mae: 0.1287
Epoch 2/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - loss: 0.0220 - mae: 0.1186 - val_loss: 0.0172 - val_mae: 0.1054
Epoch 3/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0171 - mae: 0.1047 - val_loss: 0.0185 - val_mae: 0.1098
Epoch 4/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0149 - mae: 0.0980 - val_loss: 0.0136 - val_mae: 0.0936
Epoch 5/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0134 - mae: 0.0927 - val_loss: 0.0128 - val_mae: 0.0910
Epoch 6/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0123 - mae: 0.0891 - val_loss: 0.0112 - val_mae: 0.0851
Epoch 7/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0116 - mae: 0.0865 - val_loss: 0.0108 - val_mae: 0.0837
Epoch 8/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 0.0109 - mae: 0.0838 - val_loss: 0.0101 - val_mae: 0.0808
Epoch 9/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - 

In [17]:
rnn_fully_model_dense = keras.models.Sequential([
        keras.layers.SimpleRNN(20, return_sequences=True, input_shape=[None,1]),
        keras.layers.SimpleRNN(20),
        keras.layers.Dense(1)
])

In [18]:
rnn_fully_model_dense.compile(loss="mse",optimizer="sgd",metrics=["mae"])

In [19]:
history = rnn_fully_model_dense.fit(X_train,y_train, epochs=30, validation_data=[X_valid,y_valid])

Epoch 1/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 7ms/step - loss: 0.0475 - mae: 0.1634 - val_loss: 0.0210 - val_mae: 0.1152
Epoch 2/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0161 - mae: 0.1007 - val_loss: 0.0149 - val_mae: 0.0982
Epoch 3/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 0.0119 - mae: 0.0867 - val_loss: 0.0108 - val_mae: 0.0824
Epoch 4/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0097 - mae: 0.0783 - val_loss: 0.0096 - val_mae: 0.0779
Epoch 5/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0085 - mae: 0.0734 - val_loss: 0.0084 - val_mae: 0.0728
Epoch 6/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0076 - mae: 0.0694 - val_loss: 0.0075 - val_mae: 0.0689
Epoch 7/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0070 - mae: 0.0665 - val_loss: 0.0070 - val_mae: 0.0666
Epoch 8/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0065 - mae: 0.0642 - val_loss: 0.0066 - val_mae: 0.0644
Epoch 9/30
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - lo

In [20]:
series = generate_time_series(1, n_steps + 10)
X_new, Y_new = series[:, :n_steps], series[:, n_steps:]
X = X_new
for step_ahead in range(10):
    y_pred_one = rnn_fully_model_dense.predict(X[:, step_ahead:])[:, np.newaxis, :]
    X = np.concatenate([X,y_pred_one],axis=1)

Y_pred = X[:, n_steps:]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step


In [21]:
Y_pred

array([[[ 0.5478871 ],
        [ 0.34595606],
        [ 0.09934106],
        [-0.15285155],
        [-0.3799153 ],
        [-0.5386981 ],
        [-0.62749135],
        [-0.6478457 ],
        [-0.5869417 ],
        [-0.48076555]]], dtype=float32)

In [22]:
series = generate_time_series(10000, n_steps + 10)
X_train, Y_train = series[:7000, :n_steps], series[:7000, -10:, 0]
X_valid, Y_valid = series[7000:9000, :n_steps], series[7000:9000, -10:, 0]
X_test, Y_test = series[9000:, :n_steps], series[9000:, -10:, 0]

In [23]:
model2 = keras.models.Sequential([
    keras.layers.SimpleRNN(20, return_sequences=True, input_shape=[None,1]),
    keras.layers.SimpleRNN(20),
    keras.layers.Dense(10)
])

In [24]:
model2.compile(loss="mse", optimizer="adam")
model2.fit(X_train, Y_train, epochs=20, validation_data=(X_valid, Y_valid))

Epoch 1/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - loss: 0.1156 - val_loss: 0.0517
Epoch 2/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - loss: 0.0447 - val_loss: 0.0432
Epoch 3/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0370 - val_loss: 0.0357
Epoch 4/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0334 - val_loss: 0.0337
Epoch 5/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0299 - val_loss: 0.0294
Epoch 6/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0267 - val_loss: 0.0243
Epoch 7/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0235 - val_loss: 0.0248
Epoch 8/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0204 - val_loss: 0.0189
Epoch 9/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0185 - val_loss: 0.0190
Epoch 10/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0159 - val_loss: 0.0164
Epoch 11/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 0.0147 - val_loss: 0.0141
Epoch 12/20
219/219 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step

In [25]:
series_new = generate_time_series(1, n_steps + 10)
X_new, Y_new = series_new[:, :n_steps], series_new[:, n_steps:, 0]
Y_pred = model2.predict(X_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 138ms/step


In [26]:
Y_naive = np.tile(X_valid[:, -1], 10)
print(np.mean((Y_valid - Y_naive) ** 2))
print(model2.evaluate(X_valid, Y_valid))

0.50640637
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0070
0.0069724563509225845


In [27]:
Y_naive

array([[-0.6475102 , -0.6475102 , -0.6475102 , ..., -0.6475102 ,
        -0.6475102 , -0.6475102 ],
       [-0.40070352, -0.40070352, -0.40070352, ..., -0.40070352,
        -0.40070352, -0.40070352],
       [ 0.97088933,  0.97088933,  0.97088933, ...,  0.97088933,
         0.97088933,  0.97088933],
       ...,
       [-0.2361376 , -0.2361376 , -0.2361376 , ..., -0.2361376 ,
        -0.2361376 , -0.2361376 ],
       [ 0.13786136,  0.13786136,  0.13786136, ...,  0.13786136,
         0.13786136,  0.13786136],
       [ 0.88444257,  0.88444257,  0.88444257, ...,  0.88444257,
         0.88444257,  0.88444257]], shape=(2000, 10), dtype=float32)

In [28]:
y = np.empty((10000, n_steps, 10))
for step_ahead in range(1, 11):
    y[:, :, step_ahead-1] = series[:, step_ahead:step_ahead+n_steps, 0]

y_train = y[:7000]
y_valid = y[7000:9000]
y_test = y[9000:]

In [29]:
model3 = keras.models.Sequential([
    keras.layers.SimpleRNN(20, return_sequences=True, input_shape=[None,1]),
    keras.layers.SimpleRNN(20, return_sequences=True),
    keras.layers.TimeDistributed(keras.layers.Dense(10))
])

In [37]:
def last_time_step_mse(Y_true, Y_pred):
    return tf.reduce_mean(tf.square(Y_true[:, -1] - Y_pred[:, -1]))
optimizer = keras.optimizers.Adam()
model3.compile(loss="mse", optimizer=optimizer, metrics=[last_time_step_mse])

In [40]:
# model3.fit(X_train, y_train, epochs=20, validation_data=(X_valid, y_valid))

In [41]:
class LNSimpleRNNCell(keras.layers.Layer):
    def __init__(self, units, activation="tanh", **kwargs):
        super().__init__(**kwargs)
        self.state_size = units
        self.output_size = units
        self.simple_rnn_cell = keras.layers.SimpleRNNCell(units, activation=None)

    def call(self, inputs, states):
        outputs, new_states = self.simple_rnn_cell(inputs,states)
        norm_outputs = self.activation(self.layer_norm(outputs))
        return norm_outputs, [norm_outputs]

In [42]:
model4 = keras.models.Sequential([
    keras.layers.RNN(LNSimpleRNNCell(20), return_sequences=True, input_shape=[None,1]),
    keras.layers.RNN(LNSimpleRNNCell(20), return_sequences=True),
    keras.layers.TimeDistributed(keras.layers.Dense(10))
])

C:\Users\Berkay\Desktop\ML_projects\LSTM_sentiment\Lib\site-packages\keras\src\layers\layer.py:424: UserWarning: `build()` was called on layer 'ln_simple_rnn_cell', however the layer does not have a `build()` method implemented and it looks like it has unbuilt state. This will cause the layer to be marked as built, despite not being actually built, which may cause failures down the line. Make sure to implement a proper `build()` method.
  warnings.warn(
C:\Users\Berkay\Desktop\ML_projects\LSTM_sentiment\Lib\site-packages\keras\src\layers\layer.py:424: UserWarning: `build()` was called on layer 'ln_simple_rnn_cell_1', however the layer does not have a `build()` method implemented and it looks like it has unbuilt state. This will cause the layer to be marked as built, despite not being actually built, which may cause failures down the line. Make sure to implement a proper `build()` method.
  warnings.warn(
