In [3]:
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [4]:
X = tf.range(10)

In [5]:
X

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [6]:
dataset = tf.data.Dataset.from_tensor_slices(X)

In [7]:
for item in dataset:
    print(item)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)


In [9]:
dataset = dataset.repeat(3).batch(7)
for item in dataset:
    print(item)

tf.Tensor(
[[0 1 2]
 [3 4 5]
 [6 7 8]
 [9 0 1]
 [2 3 4]
 [5 6 7]
 [8 9 0]], shape=(7, 3), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [9 0 1]], shape=(7, 3), dtype=int32)
tf.Tensor(
[[2 3 4]
 [5 6 7]
 [8 9 0]
 [1 2 3]
 [4 5 6]
 [7 8 9]
 [0 1 2]], shape=(7, 3), dtype=int32)
tf.Tensor(
[[3 4 5]
 [6 7 8]
 [9 0 1]
 [2 3 4]
 [5 6 7]
 [8 9 0]
 [1 2 3]], shape=(7, 3), dtype=int32)
tf.Tensor(
[[4 5 6]
 [7 8 9]], shape=(2, 3), dtype=int32)


In [12]:
dataset = dataset.map(lambda x:x*2)
for i in dataset:
    print(i)

tf.Tensor(
[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18  0  2]
 [ 4  6  8]
 [10 12 14]
 [16 18  0]], shape=(7, 3), dtype=int32)
tf.Tensor(
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18  0  2]], shape=(7, 3), dtype=int32)
tf.Tensor(
[[ 4  6  8]
 [10 12 14]
 [16 18  0]
 [ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [ 0  2  4]], shape=(7, 3), dtype=int32)
tf.Tensor(
[[ 6  8 10]
 [12 14 16]
 [18  0  2]
 [ 4  6  8]
 [10 12 14]
 [16 18  0]
 [ 2  4  6]], shape=(7, 3), dtype=int32)
tf.Tensor(
[[ 8 10 12]
 [14 16 18]], shape=(2, 3), dtype=int32)


In [13]:
dataset = dataset.apply(tf.data.experimental.unbatch())

Instructions for updating:
Use `tf.data.Dataset.unbatch()`.


In [15]:
new_dataset = tf.range(10)

In [16]:
new_dataset = tf.data.Dataset.from_tensor_slices(new_dataset)

In [17]:
new_dataset.filter(lambda x:x<5)

<_FilterDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [18]:
for i in new_dataset:
    print(i)

tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(9, shape=(), dtype=int32)
